security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        WilsonCorp\Bundle\Comptabilite\FraisBundle\Entity\Visiteur:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_COMPTABLE: ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_COMPTABLE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_COMPTABLE]

    providers:
        chain_provider:
            chain:
                providers: [in_memory,dbUsers]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    comptable: { password: comptapass, roles: [ 'ROLE_COMPTABLE' ] }
        dbUsers:
            entity: { class: WilsonCorpComptabiliteFraisBundle:Visiteur, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern: ^/
            anonymous: false
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
    access_control:
        - { path: ^/fichefrais/validate, roles: ROLE_COMPTABLE }